@baseUrl = http://localhost:8000/api
@token = xxx
@reset_password_token = xxxxxxxx
@refresh_cookie = xxx

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "fullName": "Jhone Doe",
  "email": "test@example.com",
  "password": "@Jhondoe123",
  "confirmPassword": "@Jhondoe123"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@example.com",
  "password": "@Jhondoe123"
}

### Save Login Response
@token = {{login.response.body.accessToken}}
@refresh_cookie = {{login.response.headers.Set-Cookie}}

### Refresh Token
# @name refresh
POST {{baseUrl}}/auth/refresh-token
Accept: application/json
Cookie: {{refresh_cookie}}

### Save New Access Token
@token = {{refresh.response.body.accessToken}}
@refresh_cookie = {{refresh.response.headers.Set-Cookie}}

### Change Password
PATCH {{baseUrl}}/auth/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "@Jhondoe123",
  "newPassword": "@Jhondoe321",
  "confirmPassword": "@Jhondoe321"
}

### Forgot Password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json
Accept: application/json

{
  "email": "test@example.com"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "token": "{{reset_password_token}}",
  "newPassword": "@Jhondoe321",
  "confirmPassword": "@Jhondoe321"
}

### Logout
POST {{baseUrl}}/auth/logout
Accept: application/json
Cookie: {{refresh_cookie}}