@token = xxxx

### GET Profile
GET http://localhost:8000/api/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### Update Profile
PATCH http://localhost:8000/api/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "fullName": "Jhone Does",
  "email": "test@example.com"
}

### Update Profile Picture
PATCH http://localhost:8000/api/profile/picture
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profilePicture"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./files/avatar.jpg
--WebAppBoundary--